$(document).ready ->
  $(window).on 'scroll', (e) ->
    body = document.body
    html = document.documentElement
    if $(window).scrollTop() % 2 == 0
      height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight)
      win_height = Math.max(document.documentElement.clientHeight, window.innerHeight or 0)
      width_px = $("li.done .dot").offset().left - $("li.basic .dot").offset().left
      console.log("scrollTop: " + $(window).scrollTop())
      console.log("height: " + height)
      console.log("win_height: " + win_height)
      $('#scrollBar').css width: ($(window).scrollTop() *  width_px / (height - win_height)) + 'px'
      screen_perc = $(window).scrollTop() * 100 / (height - win_height)
    return
  return

# ---
# generated by js2coffee 2.1.0